import AppKit

/// Turns pasteboard contents into a `ClipPayload`, and a clip back into pasteboard contents.
///
/// Priority when several representations are present: file URLs, then images, then rich
/// text, then plain text (a lone http/https URL becomes a `.url` clip).
public enum ClipReader {
    /// Marker Stash puts on everything it writes, so the watcher can skip its own writes.
    public static let stashMarker = NSPasteboard.PasteboardType("xyz.machud.stash.marker")

    /// nspasteboard.org markers: content an app asks clipboard managers not to record
    /// (passwords, transient or auto-generated data).
    public static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    /// Largest blob recorded (images bigger than this are skipped).
    public static let maxBlobBytes = 32 * 1024 * 1024

    /// Whether the pasteboard's contents should not be recorded at all.
    public static func isConcealed(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { concealedTypes.contains($0) }
    }

    public static func read(_ pasteboard: NSPasteboard) -> ClipPayload? {
        guard let types = pasteboard.types, !types.isEmpty else { return nil }

        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipPayload(kind: .files, text: urls.map { $0.path(percentEncoded: false) }.joined(separator: "\n"),
                               fileURLs: urls)
        }

        if let png = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff).flatMap(pngData) {
            guard png.count <= maxBlobBytes else { return nil }
            return ClipPayload(kind: .image, blobData: png, blobExtension: "png", imageSize: pixelSize(png))
        }

        let string = pasteboard.string(forType: .string)
        if let rtf = pasteboard.data(forType: .rtf), rtf.count <= maxBlobBytes {
            let plain = string ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
            if let plain, !plain.isEmpty {
                return ClipPayload(kind: .richText, text: plain, blobData: rtf, blobExtension: "rtf")
            }
        }

        if let string, !string.isEmpty { return .text(string) }

        if let url = pasteboard.string(forType: .URL), !url.isEmpty { return ClipPayload(kind: .url, text: url) }
        return nil
    }

    /// A single http(s) URL with no whitespace.
    public static func isWebURL(_ string: String) -> Bool {
        let s = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !s.isEmpty, !s.contains(where: \.isWhitespace), let url = URL(string: s),
              let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https", url.host != nil else {
            return false
        }
        return true
    }

    /// Writes `clip` to `pasteboard` (clearing it), tagged with `stashMarker`. `blobURL` is the
    /// clip's blob file, if any. Returns false if nothing could be written.
    @discardableResult
    public static func write(_ clip: Clip, blobURL: URL?, to pasteboard: NSPasteboard) -> Bool {
        pasteboard.clearContents()
        var ok = false
        switch clip.kind {
        case .files:
            let urls = (clip.fileURLs ?? []) as [NSURL]
            ok = !urls.isEmpty && pasteboard.writeObjects(urls)
        case .image:
            if let blobURL, let data = try? Data(contentsOf: blobURL) {
                pasteboard.declareTypes([.png], owner: nil)
                ok = pasteboard.setData(data, forType: .png)
                if let tiff = NSImage(data: data)?.tiffRepresentation { pasteboard.setData(tiff, forType: .tiff) }
            }
        case .richText:
            if let blobURL, let rtf = try? Data(contentsOf: blobURL) {
                pasteboard.declareTypes([.rtf, .string], owner: nil)
                ok = pasteboard.setData(rtf, forType: .rtf)
            }
            if let text = clip.text { ok = pasteboard.setString(text, forType: .string) || ok }
        case .url:
            if let text = clip.text {
                ok = pasteboard.setString(text, forType: .string)
                pasteboard.setString(text, forType: .URL)
            }
        case .text:
            if let text = clip.text { ok = pasteboard.setString(text, forType: .string) }
        }
        mark(pasteboard)
        return ok
    }

    /// Writes plain text, tagged with `stashMarker`.
    public static func write(text: String, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        mark(pasteboard)
    }

    private static func mark(_ pasteboard: NSPasteboard) {
        pasteboard.addTypes([stashMarker], owner: nil)
        pasteboard.setData(Data(), forType: stashMarker)
    }

    static func pngData(_ tiff: Data) -> Data? {
        NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
    }

    static func pixelSize(_ data: Data) -> CGSizeCodable? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        return CGSizeCodable(width: Double(rep.pixelsWide), height: Double(rep.pixelsHigh))
    }
}
